name: CallShield

options:
  deploymentTarget:
    iOS: "15.1"
  xcodeProjPath: ios/callshieldnative.xcodeproj
  bundleIdPrefix: com.alessiobianchini
  settingPresets: all

settings:
  base:
    DEVELOPMENT_TEAM: SK68SF94T9
    SWIFT_VERSION: 5.9
    IPHONEOS_DEPLOYMENT_TARGET: 15.1

targets:
  callshieldnative:
    type: application
    platform: iOS
    sources:
      - path: ios/callshieldnative
        type: group
    settings:
      base:
        INFOPLIST_FILE: ios/callshieldnative/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.alessiobianchini.callshieldprotect
        CODE_SIGN_ENTITLEMENTS: ios/callshieldnative/callshieldnative.entitlements
    dependencies:
      - target: CallShieldDirectory
        embed: true
      - sdk: CallKit.framework

  CallShieldDirectory:
    type: app-extension
    platform: iOS
    sources:
      - path: ios/CallShieldDirectory
        type: group
    settings:
      base:
        INFOPLIST_FILE: ios/CallShieldDirectory/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.alessiobianchini.callshieldprotect.CallShieldDirectory
        CODE_SIGN_ENTITLEMENTS: ios/CallShieldDirectory/CallShieldDirectory.entitlements
        # Important: make sure it can be packaged
        SKIP_INSTALL: "NO"
    dependencies:
      - sdk: CallKit.framework
